FROM python:3.10

RUN apt-get update -y
RUN apt-get install -y wait-for-it
RUN pip install poetry
RUN pip install waitress
ADD ./pyproject.toml .
ADD ./poetry.lock .
RUN poetry export -o requirements.txt
RUN pip install -r requirements.txt
COPY . /app
WORKDIR /app

CMD sh entrypoint.dev.sh
